// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Entity
{
    public partial class Test
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? Times { get; set; }
    }
}